### ISSUE TITLE
recommended way to start tour programmatically

### ISSUE THREAD

**Issue by bdkent** [benmarch/angular-ui-tour#1]
What is the recommended way to start tour programmatically?

For example if I want to start the tour 1 or two second after the page loads?

**Comment by benmarch** [comment]
Hey @bdkent, I think right now the only way would be to access the scope (or child scope) that the tour is on, and in a $timeout call scope.tour.start().

If you have a suggestion for another way to do it (events or service possibly) please let me know.

**Comment by bdkent** [comment]
What if the `ui-tour` had an attribute that acted as a callback function once the `tour` object was initialized? That should be enough of a hook to let someone write their own `$timeout` or whatever.

My current hacky work-around is a [silly directive](https://gist.github.com/bdkent/ddb200bb465fb78333e7) but I would love a better solution!

**Comment by benmarch** [comment]
I added a hook for onReady that is called immediately after the tour is initialized and attached to the scope. Since all events are evaluated against the tour's scope you can pass the tour itself into the onReady handler so you don't have to try to access it indirectly:

    <div ui-tour on-ready="onTourReady(tour)"...>
        <div tour-step ui-tour-title="No Silly Directive" ui-tour-content="No more need for inverted control. Thanks for the suggestion, @bdkent!"></div>
    </div>

I think I will also create a service that can be used for accessing the tour (or multiple tours) so that callbacks can be added throughout the app's lifetime. I might even turn the tour instances into EventEmitters so handlers can be added more dynamically. 

**Released 0.0.2 with this change.**
