### ISSUE TITLE
best practices for input elements as tour-steps

### ISSUE THREAD

**Issue by lordzappo** [benmarch/angular-ui-tour#108]
**I am using the _exact_ versions of the following libraries:**

* AngularJS: 1.5.11
* Angular Bootstrap: 2.4.0
* Angular UI Tour: 0.7.0

**I have installed this library via:** bower

**I have observed the following behavior:**

when i use the tour-step directive on INPUT or SELECT elements, the ng-model bindings now go to the new ui-tour child scope, not the parent scope, and the page breaks.

I dont think this is a bug, I just want to know best practices to get this to work the way I expect, if i want to make input elements tour-steps.

**Comment by benmarch** [comment]
Hey @lordzappo, I will investigate a better workaround for this in the next release--it has come up a few times recently. I think the best thing for now is to declare your model on the parent scope as early as possible so that the children scopes use their prototypes instead of creating their own models. If your parent scope uses a controller, then just declare it in the controller definition. If it is a directive, then declare it in a prelink function.

Sorry for the inconvenience, let me know how it goes.

-Ben

**Comment by lordzappo** [comment]
I thought I was doing what you suggested already, (I read several of your closed tickets before posting)

but this document clarified where i was going wrong: https://github.com/angular/angular.js/wiki/Understanding-Scopes

i was using simple primitives in the controller, which weren't correctly inheriting.  i changed my input properties to be part of a javascript object, getting the  myobject.property syntax into the html portion, and that fixed my issue quickly/easily.
