### ISSUE TITLE
Backdrop is not properly hidden when using browser's navigation

### ISSUE THREAD

**Issue by kwieckowski-neducatio** [benmarch/angular-ui-tour#109]
**I am using the _exact_ versions of the following libraries:**

Demo page

**I have observed the following behavior:**

When demo tour is navigating to another view (nextStep option) and I navigate back with my browser's interface, the tour stops but the backdrop stays in the same position.

**This is how I expected it to behave:**

Backdrop should be cleared when tour is destroyed.

**Comment by benmarch** [comment]
Version 0.8.0 has been released, please verify that this issue has been resolved. Note that there are a few breaking changes that might need to be addressed: https://github.com/benmarch/angular-ui-tour#versions.

There is a configuration that needs to be set for this to work. I tried enabling it by default, but it broke some of my unit tests because it sets up a watch in the run stage. The details are in the README, but here is the code snippet you need to add:

```
app.config(function (TourConfigProvider) {
    TourConfigProvider.enableNavigationInterceptors();
});
```
