### ISSUE TITLE
Issue regarding angular-ui-tour with modal window

### ISSUE THREAD

**Issue by m101010** [benmarch/angular-ui-tour#11]

**Comment by benmarch** [comment]
Could you elaborate, please?

**Comment by m101010** [comment]
Hi benmarch,

first of all - i really like this plugin! Thank you for your great work.

I was able to use it to set up a tour for a small page without any problems.
As the next step i was trying to set up another tour inside a modal window (https://angular-ui.github.io/bootstrap/#/modal).
As I am rather new to angular and web development as a whole i am unfortunately confronted with a problem i cannot solve on my own.

As soon as i open the modal window i receive the following error message:
"Error: $compile:ctreq
Missing Required Controller
Controller 'uiTour', required by directive 'tourStep', can't be found!" (https://docs.angularjs.org/error/$compile/ctreq?p0=uiTour&p1=tourStep)

Am I missing something simple here? 

I am trying to set up a fiddle on this right now :)

**Comment by benmarch** [comment]
Hi @m101010, it sounds like you might have a tour step that is not within any tour. This might have something to do with the way that Angular UI Bootstrap creates modal windows. I would start by inspecting the DOM to see if the tour step inside the modal has an ancestor that contains a tour directive.

**Comment by m101010** [comment]
Hi @benmarch, thank you for your hint. 
I checked this over and over again and everything seemed fine.

For now i resolved the issue by wrapping the whole modal content in another div where i place the ui-tour directive. 
With this i can place tour-steps on most of my elements. Some other elements are still not working (for example "uib-tab-heading" and every child of such). At one point I got the error message that there are two directives that want to create an isolated scope which will result in a conflict.
Maybe this is the whole underlying reason.

Another problem happens if I try to do a tour-step together with the "backdrop"=true option.
In this case the tour-popup is no longer clickable and is vanishing behind the gray backdrop layer. I guess there is a compatibility issue with the backdrop of the modal window. 

If i figure this out i will let you know. Unfortunately until now i don't have any success on this.
Thanks and regards

**Comment by benmarch** [comment]
Hi @m101010, w.r.t. the backdrop, you can set the backdrop z index of the tour backdrop (and likely the modal backdrop) to a value that might let it work; however, putting a tour in a modal sounds like a questionable design. The other issues are related to how you are using the directives, but since tour steps do not require isolate scopes it is not related to this plugin. I think it might be useful to read through the [angular directive documentation](https://docs.angularjs.org/guide/directive). It seems to me that these issues are mostly unrelated to this plugin, so I am going to close this issue. Good luck!
