### ISSUE TITLE
End Tour Event during Clicks inside DIV with Backdrop

### ISSUE THREAD

**Issue by Mr-Anonymous** [benmarch/angular-ui-tour#116]
I have a very similar problem related to closed issue: https://github.com/benmarch/angular-ui-tour/issues/53

I am using the `tour-step-backdrop="true"` around a div wrapper that has Buttons and Anchor links inside it. If a users clicks on the Anchor links inside that DIV, the page goes to the next state, the tour popover disappears and the backdrop stays. Instead of adding an event listener in each of these controllers to manually disable button clicks and anchor's `ng-clicks` when the tour event is on, is there a global method to end tour automatically if there was any interaction or state change? Something similar to `tour-step-on-backdrop-click="tour.end()"` but to stop tour when user clicks inside the div and not just the backdrop?

Thanks,
Neel.

**Comment by benmarch** [comment]
Hey Neel,

I think I understand the issue that you are having, but I can't think of the best way to work around it. You might be able to use a global `$onStateChangeStart` (or whatever the proper router event is) handler to pause or end the tour. This would only be an issue if you are using the tour over multiple pages because it would interfere with navigating to the next step.

Try this for now: add the `$onStateChangeStart` handler and use `tour.pause()`. That _shouldn't_ interfere with navigation, but let me know if you run into issues.

Thanks,
Ben

**Comment by Mr-Anonymous** [comment]
Thank you @benmarch 

I will go with the `$onStateChangeStart` watch for now. However, I am also thinking perhaps I should try and rewrite these pages and create separate demo pages which doesn't have working Anchors and Buttons as a work around. This way I can also show dummy demo data on pages during the tour.

Thank you for your input. Stopping or pausing the tour during `$onStateChangeStart` makes sense if I dont see the rewrite of these tour pages.

Thanks,
Neel.
