### ISSUE TITLE
Using tour steps in ng-repeat

### ISSUE THREAD

**Issue by mohit-github** [benmarch/angular-ui-tour#120]
I am not able to work around an issue. When I put a tour step inside a ng-repeat element, on clicking the next button it moves to the similar element in the ng-repeat.
I want to know if I can override the next step, to move it to a different step that I can explicitly define on the tour step.
In simple terms, I want to control where the next button takes the tour.

**Comment by benmarch** [comment]
You will probably have to play around with the `tour-step-enabled` option to get it to work right. If you just want to show it for the first one, for example, just use: `tour-step-enabled="$index === 1"`.

Since this is not really a bug (since creating a tour step in an ngRepeat will naturally create multiple steps and move through them in order) I am going to close this issue.

**Comment by mohit-github** [comment]
This, tour-step-enabled="$index === 1" doesn't work

**Comment by alexpireddu** [comment]
Seems it makes a comparison with a string,
`step.enabled = isEnabled !== 'false';`
so with interpolation it should work 
`tour-step-enabled="{{$index === 1}}"`
