### ISSUE TITLE
No Step

### ISSUE THREAD

**Issue by wiemKh** [benmarch/angular-ui-tour#166]
hi i'm new in angularjs i want to integrate angular ui tour in my application , it worked fine but  when i open my application the tour always shows so i want  only when  the user click on link the tour start  
this is my link
```
 <a ui-tour ng-controller="MyTourCtrl"   ui-tour-template-url="'views/tour-step-template.html'"  ng-click="tour.startAt('adviceList')>
               demo </a>  
```
and in other view i have 
```
<div ng-controller="MyTourCtrl" ui-tour ui-tour-on-ready="tour.start()" ui-tour-template-url="'views/tour-step-template.html'">
                          <div tour-step="'adviceList"  tour-step-title=""  tour-step-content=""
                      tour-step-order="1" tour-step-placement="left" tour-step-on-next="navigateToAndwaitFor(tour, 'adviceList', 'adviceList')></div>
                                        </div>
```
but when i click the link i got error No step.

**Comment by benmarch** [comment]
Hey @wiemKh, this could be caused by a number of issues, but it isn't an issue with this module. Try these, if they don't work, please look through the README and closed issues:
- Every `ui-tour` directive you use creates a new tour. So your link is creating a new tour with 0 steps (there are no steps defined within your link). This is the main issue, but you will still run into issues:
- Don't set an `ng-controller` on the same element as the `ui-tour`. This will create 2 scopes, and the controller scope will not have access to the tour scope.
- Move your link inside the other `ui-tour` div, and remove the `ui-tour-on-ready="tour.start()"` from the div.
- To create multi-view tours, move the `ui-tour` directive to the body element, or any ancestor element of ngView. Then create the steps anywhere, and you can keep the tour start button/link anywhere in there as well.

**Comment by wiemKh** [comment]
thank you a lot  ben  , it worked now :) but i still have a problem that ( i dont know how to explain it lol ) 
for exemple in view 1 i have step 1 with content hello 
in view 2 i have step2 with content hello2
when the user is in view 2 and then click button back of navigateur to be back to view 1 .
in view 1 we have hello and hello 2 (both)
i want hello 2 be only  on view 2 
how i can do that?
i hope you undrestand me 
![image](https://user-images.githubusercontent.com/25384199/34114347-de6f2f02-e412-11e7-9f75-35a2a7529a06.png)
