### ISSUE TITLE
popover appearing behind 

### ISSUE THREAD

**Issue by dander401** [benmarch/angular-ui-tour#17]
Im, not sure if this an actual bug or just something that you should note in the documentation. 

When specifying the tour to use a back drop, the back drop will cover the popovers unless they are appended to the body element. This makes since with how html and z indexes work, and I don't if you can actually get around it.

....btw... thanks for the super fast response yesterday, the fixes were great.

**Comment by benmarch** [comment]
Hey @dander401, no problem, always happy to help.

With respect to the stacking, it very much depends on how your page is set up. If your popovers are in a child stacking context then yes, they will be behind the backdrop. Take a look at the [demo page](http://benmarch.github.io/angular-ui-tour), you will see that the popovers are above the backdrops because there is only one stacking context (the root). I have played around with creating faux backdrops like making the `outline` property of the popover extremely large and styled like a backdrop, but that causes major performance problems. Backdrops in general are quite tricky, and it would be nice if something were added to the CSS spec that would standardize their creation. Here is a [resource about stacking contexts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context); I was forced to acquire a deep understanding of them when I was working on an old project at work because the design was really intricate with absolute and fixed elements. I will look into alternatives, but I don't expect to find a good solution for creating a reliable backdrop. If appending to body is working for you then I think it would be best just to go with that.

Thanks,
Ben

**Comment by dander401** [comment]
I agree with all of that, it just caught me off guard today

**Comment by benmarch** [comment]
Hey @dander401, I made a note in the readme to use appendToBody whenever using a backdrop. It's not an idea solution, but it should work. Thanks for pointing this issue out!

**Comment by dander401** [comment]
I think that's a great solution as long as you are using angular uis pop over.
