### ISSUE TITLE
make _getCurrentStep a supported method

### ISSUE THREAD

**Issue by dander401** [benmarch/angular-ui-tour#18]
Feature Request

Our site will have several tours, and instead of of duplicating the code to tracking each of their pause or ended states, it would be awesome if I could safely use _getCurrentStep ( or something like it ) to see if I need to call start or resume when the tour is requested. 

edit: Actually... could there just be an option to hide the pause button?

**Comment by benmarch** [comment]
Hey @dander401, I think what I will do is expose the tour status which is either "on" (running), "paused", or "off" (ended) which should help with determining which action to take. I think exposing the step could allow developers to accidentally break the tour, which is why it was exposed as a debugging method only. I could return a copy/read-only version of the current step if that would be useful? 

For hiding the pause button, you could override the [template](https://github.com/benmarch/angular-ui-tour/blob/master/app/templates/tour-step-template.html) and use an ngIf/ngShow/ngHide to control the pause button visibility programmatically.

**Comment by dander401** [comment]
That sounds awesome

**Comment by benmarch** [comment]
Hey @dander401, the tour now exposes the status as `tour.getStatus()`, and you can use the `tour.status` enum to determine what the status is. For example:
```js
if (tour.getStatus() === tour.status.PAUSED) {
    tour.resume();
}
```

I have also exposed `tour.getCurrentStep()` which returns a copy of the current step to avoid accidentally breaking the tour. You can still pass this copy back into any API function that accepts a step as long as the step ID is set.

Released 0.4.0.

**Comment by dander401** [comment]
This is amazing. Thanks!

**Comment by benmarch** [comment]
No problem, thank you for helping to debug!!
