### ISSUE TITLE
Add steps from the controller or specify the tour a step belongs to

### ISSUE THREAD

**Issue by dander401** [benmarch/angular-ui-tour#25]
We are wanting to build several independent tours to explain different parts of our site. As well as one that explains the site from a birds eye view. We haven't run into this issue yet, but we are afraid of adding a tour step in multiple tours ( due to the umbrella tour having many nested views ). 

So the use case we are fearing looks something like this
```
Tour Umbrella
    Step U1
    Tour Child 1
            Step C1-1
            Step C1-2
    Step U2
    Tour Child 2
            Step C2-1
            Step C2-2
```
Will the Steps C1 and C2 be added Tour Umbrella?

If so, is there anyway to avoid this... or make it clear which tour a step belongs to?

**Comment by benmarch** [comment]
Hey @dander401, it will not add steps to both tours, and this is because of the way that Angular scopes the DOM. When there is a directive that `require`s a controller, it calls `element.controller(<controller name>)` which will ascend the DOM until it finds an element that has the required controller bound. In this case, the tour step `require`s `uiTour`, so Angular will look at the step's ancestors until it finds a tour, and then it will use that and stop ascending. It certainly won't add it to both tours, but it might add to the umbrella tour if the nested step is loaded in the DOM before the nested tour (although I would be surprised if you have it set up that way). Let me know if you notice that it is doing something unexpected and I can help you debug.

**Comment by dander401** [comment]
@benmarch thanks for the response. That makes sense. Like I said, we havent gotten to that issue yet, was just curious from a code maintenance stand point
