### ISSUE TITLE
Problem with ngFilter

### ISSUE THREAD

**Issue by cesarcosta99** [benmarch/angular-ui-tour#32]
I put a step with _backdrop_ and _prevent scrolling_ in a input field that has a model to apply a search filter in a `ng-repeat` and the filter was not working anymore. If I remove the step the filter works.

The `ng-model` works, the data is passing, but it's not being filtered. And I tried to put the step on a wrap of the input field also, didn't work.

**Comment by benmarch** [comment]
Hmm, does it break even when the tour is off, or only when the step is displayed?

**Comment by cesarcosta99** [comment]
It's not working at any point.

**Comment by benmarch** [comment]
Ok, sounds like it might be caused by the inherited scope. The tour step creates a new scope that inhertis from the scope in which it's placed. It sounds like your search box is updating a property on the scope which is then used in the ngRepeat filter. Because there is a new scope, it is initializing the property on the inherited scope instead of the parent (which is shared by the ngRepeat). Try initializing the scope property in your contoller as an empty string, that way both the search box and ngRepeat will share the same reference. This is generally a good practice as scope inheritance can cause major problems if things aren't initialized explicitly in the expexted scope. Let me know if that solves the problem, if not, can you paste some markup and possibly controller code here?

**Comment by cesarcosta99** [comment]
I think you are totally right, but I'll can test it only on Monday. I've already read about what you said but I didn't have time to implement this in my project yet, seems it's the right moment to do it. I'll keep you informed, thanks a lot for the explanation!

**Comment by benmarch** [comment]
Cool, let me know!

**Comment by cesarcosta99** [comment]
I've just started to implement good practices in my project and the controllerAs solved the problem, I'll move my scope variables to the top and wrap my components in a IIFE. Thanks for the tip.
