### ISSUE TITLE
Ability to manually insert or append tour with manual options

### ISSUE THREAD

**Issue by ronnyek** [benmarch/angular-ui-tour#40]
Is there anyway to say add a step pointing at this html element id? I've got elements shared across many pages, and want to have tour steps on the first page, but not any subsequent pages.

I love how you define steps in the demos, would just prefer not to have them bound on the shared template, and call that out as additional steps, or something.

**Comment by ronnyek** [comment]
Actually I see reference of tour steps being able to be defined in config blocks, do you have an example of that?

**Comment by benmarch** [comment]
Hey @ronnyek, currently there is no way to add steps imperatively with this library. I was resistant to this concept for a long time because imperative Javascript, while easy to write, is a PITA to understand and debug. I would be willing to add this feature as a "swim at your own risk" sort of deal, but I am not sure if it would be possible using UI Bootstrap which requires the directive to be present during the compile phase. I will play around with it and let you know if I come up with anything.

**Comment by ronnyek** [comment]
Well the HTML Elements would exist at the time of the compilation, but only because the reused ui is effectively like server side includes... (probably hardly a use case most people would need). In any case, I think I could probably get around it by having some additional check or something as to whether or not to include a step on the tour. If tour-step declarative definition has a disabled or something I could feed a scope property or something... just thinking out loud.

Seems like a niche case... I almost wouldnt worry too much about it

**Comment by benmarch** [comment]
There actually is a `tour-step-enabled="{{shouldStepShow}}"` option for tour steps precisely for this use case. I understand that you would rather not put the markup in the shared templates at all, though. If tourStepEnabled works for you that's awesome, but I will still look into adding imperative steps since I just recently caved to allowing adding imperative tours 😸

**Comment by benmarch** [comment]
I am hoping to add basic version of this feature in the 0.8.0 release. If it does not make it to 0.8.0 then it will definitely be in 0.9.0. Sorry for the long wait, but I want to make sure it is done correctly, and it cannot be as long as I am using Angular UI Bootstrap to initialize the popovers.

**Comment by benmarch** [comment]
Version 0.8.0 has been released, please verify that this issue has been resolved. Note that there are a few breaking changes that might need to be addressed: https://github.com/benmarch/angular-ui-tour#versions.

There is now a `createStep()` method on tours. See the README for details.
