### ISSUE TITLE
GoTo function

### ISSUE THREAD

**Issue by amanraghubansi** [benmarch/angular-ui-tour#42]
Hi,
I try to use goTo function,so i am calling below code  within onNext function provided by API.
uiTourService.getTour().goTo('lastStepId').......
last step is shown as expected but End tour button is not working...
Observation : When we click on end tour in last step,tour is getting terminated and started again at step mentioned in goTo function?
PFA screenshot of error.
![cropped](https://cloud.githubusercontent.com/assets/9050585/14459744/545c3898-00d7-11e6-9a70-ff897caef4c7.jpg)

**Comment by benmarch** [comment]
Hi @amanraghubansi, I don't recommend navigating inside of an onNext() hook because it breaks the flow the tour. I was able to produce a similar issue by navigating to the last step within an onNext() and it is to be expected. If you want to navigate to the last step, ensure that the order is set properly, or if you want to jump to it, create an action button that does the navigation.
