### ISSUE TITLE
Current active element

### ISSUE THREAD

**Issue by amanraghubansi** [benmarch/angular-ui-tour#43]
Hi,
I am  not able to get any info. in code about element on which tour step is activated currently.If you can 
1. provide an option to add class dynamically to currently active host element in tour step or add static class to current host element.
2. can provide a host element object in callbacks mentioned in API i.e onNext,onPrev, onStart,onEnd, onShow, onShown etc,,,so that i can made changes as required in my code w.r.t acitve host element.

**Comment by benmarch** [comment]
I can look into adding a class to the active tour step, that's a great suggestion, thank you! In the meantime, you can get the element by grabbing a reference to the current step and looking at the `element` property (tourStep.element). There are multiple ways to get a reference to the step... if you put a lifecycle hook (onNext, onPrev, etc) on the step itself, you can pass it in as an argument like this:

```html
<div tour-step tour-step-on-next="doSomething(tourStep.element)">...</div>
```

If your hooks are on the uiTour element, then the step won't be available directly, but you can grab it off of the tour by passing that in:

```html
<div ui-tour ui-tour-on-next="doSomething(tour.getCurrentStep().element)">...</div>
```

In either case, it might be best to pass just the step or just the tour into `doSomething()` and then traverse the graph in the controller instead of in the HTML.

**Comment by benmarch** [comment]
Version 0.5.4 includes these changes.
