### ISSUE TITLE
uiTour doesn't work for views dynamically loaded.

### ISSUE THREAD

**Issue by kiranbinmaygh** [benmarch/angular-ui-tour#5]
Hi,

I have a scenario like this and I found that uiTour is not working for me:

* A layout page with ui-tour directive set on <body>
* A view gets loaded in the body that has a side menu and the content area.
* My side menu has a controller and the content area has another controller.
* I want a button on the content area that should trigger the tour and I plan to define a `<div>` with ui-tour set and all the menu items will be contained inside the `<div>`.

I get an error that reads - 
TypeError: Cannot read property 'onShow' of undefined
    at self.showStep (angular-ui-tour.js:352)
    at self.start (angular-ui-tour.js:260)
    at $parseFunctionCall (angular.js:12404)
Hope it makes sense.

For a visual illustration - I want the tour to work against the menu items on the left when I click on start tour as illustrated here - http://themicon.co/theme/angle/v3.2/backend-angular/#/app/tour

The tour on this site works for elements that are defined in the container where the Start tour button is. I want to define the tour elements to be defined against the menu items while keeping the button as it is now.

Regards,
Kiran Banda

**Comment by benmarch** [comment]
Hi Kiran,

Very sorry for the delay, I just got back from a long vacation. It looks to me like the tour is starting before any tour steps are loaded since "undefined" should be the first step in the tour. Check to make sure that the steps are loaded into the DOM before starting. Since there are no other errors, I am assuming that the steps are _not_ nested within a directive that requires an isolate scope (which could also cause this error, but would have one before it as well.) Let me know if that does not solve this problem, or if there is another error in the console.

Thanks,
Ben

**Comment by benmarch** [comment]
Hi @kiranbinmaygh, is there any update to this?

**Comment by benmarch** [comment]
Hi @kiranbinmaygh, I am going to close this issue and ask that you retest in 0.3.1.
