### ISSUE TITLE
Define steps in config block

### ISSUE THREAD

**Issue by bondseid** [benmarch/angular-ui-tour#71]
I believe there was a previous topic on this, but will you be adding support for steps configurable in the config blocks rather that directly as html directive elements?

**Comment by benmarch** [comment]
Hi @bondseid, unfortunately this is very difficult because it relies on Angular Bootstrap's popovers, which means the popover directive must be on the element when Angular compiles it in order to work. This would require a DOM listener that would look at every DOM node inserted event and add the proper attributes when it finds a target, then compile it. This could result in slow performance and potentially break Angular scope chains. I am still playing around with it though, but I am going to keep tracking the work in #40.
