### ISSUE TITLE
Getting parse.syntax error on tour start inside my directive

### ISSUE THREAD

**Issue by megabyzus** [benmarch/angular-ui-tour#72]
**I am using the _exact_ versions of the following libraries:**

* AngularJS: 1.5.8
* Angular Bootstrap: 2.1.2
* Angular UI Tour: 0.5.4

**I have installed this library via: CDN:

`        <script type="text/javascript" src="https://cdn.rawgit.com/d-oliveros/ngSmoothScroll/v2.0.0/lib/angular-smooth-scroll.js">
        </script>

        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular-sanitize.min.js"></script> 
        <script type="text/javascript" src="https://cdn.rawgit.com/benmarch/ez-ng/0.1.8/dist/ez-ng.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular-hotkeys/1.7.0/hotkeys.min.js"></script>     
        <script type="text/javascript" src="https://cdn.rawgit.com/benmarch/angular-ui-tour/0.5.4/dist/angular-ui-tour.min.js"></script>   `

I have observed the following behavior:

I am attempting to activate the tour popup inside my directive/partial.  The top of my directive's partial I have added this simple HTML block below:

```
<div ui-tour>
	<div
		id="mainMenu" 
		tour-step tour-step-title="Main Menu" 
		tour-step-content="Navigate the site using this menu." 
		tour-step-order="0" 
		tour-step-placement="right">
	</div>
	<span ng-click="startTour()">ui tour block</span>	
</div>
```

In the directive's controller I have this (not sure if I need to invoke tour.start() or not, but I did).

```
$scope.startTour = function () {
      this.tour.start();
};
```
Invoking the above throws:
`Error: [$parse:syntax] http://errors.angularjs.org/1.5.8/$parse/syntax?p0=%7B&p1=is%20an%20unexpected%20token&p2=16&p3=%7BNaNn%3A%isOpen%20%7D%20%7B%in%3A%isOpen()%20%7D&p4=%7B%in%3A%isOpen()%20%7D`

This is how I expected it to behave:  I expected the first popup to show.

**Additional notes/code: Also, our app is a single page app using ui-router.  We are moving forward with ui-tour on the assumption that this library doesn't have anything exceptional wrt to SPAs.   Are we correct?  Also,  it would be great if an SPA example were added as well where ui-router name an d paths (including adjunct parameters passed to the state) we available.

**Comment by benmarch** [comment]
Hi @megabyzus, you will have to update this library to 0.6.0 in order to use Angular Bootstrap 2.x. 

This library does work well with SPAs, and I have seen examples of UI Router integration in the wild; I'll see if I can track one down.

**Comment by megabyzus** [comment]
@benmarch,  thanks for the prompt reply.  I'm using AJS 1.5.8.  Does this still require ui-tour 0.6.0?

**Comment by megabyzus** [comment]
@benmarch Again, thanks.  For ui-router based SPAs what do you recommend as a ui-tour strategy? Separate ui-tour per router state, or a single ui-tour at body?  Apologies asking this here.

**Comment by benmarch** [comment]
It depends on your use case. If you want a single, flowing experience, use a single tour. If you want separate instructions on each page, use multiple tours. I would ask myself how many times I would like the user to trigger tours. Although, even if you go with multiple tours you can programmatically trigger each one when the previous one ends, so it wouldn't be restrictive if you go that way. UI Tour was originally designed to be a single, flowing tour, so I'm honestly not sure what obstacles you would encounter by creating a bunch of different tours. If you go with multiple tours, I would love to hear about how you implement it, and any issues and solutions you discover. (Sorry, that was me thinking out loud 😸 )

**Comment by megabyzus** [comment]
Thanks.  Many of the directives in SPA have corresponding partials that require tours.  However, these partials are often instantiated via AJS ng-if conditionals. Will ng-if's tour-steps, deep within the bowls of the APS work under as <body ui-tour....>? A cursory test shows that the ui-tours have to be within the same ng-if block for the tour-steps to work?  Thoughts?

**Comment by benmarch** [comment]
The steps should be ok if there is a single tour set on the body. Angular automatically compiles templates added by ngIf, and the steps are registered after compilation (conversely, they are unregistered when removed from the DOM). Since the steps don't use the scope, they shouldn't have to be within the same ngIf as the tour; however, if you are trying to access the tour or the tour step from the scope it might not be available. There are ways around that using the uiTourService though.

**Comment by megabyzus** [comment]
Thanks.  So this is what I'm finding: I am successfully starting `<body ui-tour=...>` (`ui-tour-on-ready` is triggered), once, at some point later, the directive deep within the SPA is born (by some ngIf flag),  I have to $timeout(0) wait for angular to digest that flag and create the DOM (and the tour-steps within) and then start() (not resume()) the tour again for that tour-step to show:

```
$scope.castDataReady = true;

$timeout(function () {

	var tourPromise = uiTourService.getTour().start();

	tourPromise.then(function(results) {

		console.log('tour started');

	}, function (results) {

		console.log('tour start failed');
	});							

},0);
```

**Comment by benmarch** [comment]
When you start it the first time is there already an active step? Does the next step enter the DOM while a step is active? Is the order of the seconds step later than the first?

**Comment by megabyzus** [comment]
@benmarch No,  the popover (tour-step) does not show the first time in the unborn directive.  It does show if I move the tour-step outside of an ngIf.

**Comment by benmarch** [comment]
Can you provide a code sample?

**Comment by megabyzus** [comment]
I'll work on a plunkr.  But before I do that, just want to confirm the code I've provided above is not sufficient to debug.  Please confirm.

**Comment by benmarch** [comment]
It's a little out of context. I would like to see the markup and config. It might have more to do with timing: as steps appear, they are added to the tour, and tour navigation uses the most current step list. If the tour is started before the step exists, it will just end. If you navigate from the last step before the next one exists, it will also end.

**Comment by megabyzus** [comment]
@benmarch here's a simple [plunkr](https://plnkr.co/edit/80RN2V) that simulates the question.
I have added a note inside index.html that summarizes previous notes.

I have started a tour on `<body ui-tour>` within my top level app controller.

**Scenario 1** (this is my scenario): I also have a tour-step(id=1) within an uninstantiated `<sample-directive>` (ng-if). The associated tooltip doesn't show even though the tour was previously started outside of the directive UNLESS I `getTour().start()` again inside the directives controller while within a $timeout(0) to absorb the AJS $digest. Note, the directive itself is instantiated after another top level $timeout simulating, say, an $http call inside app.js. 

**Scenario 2** (observation only): I am observing that if tour-step(0) DOM element were uncommented (<p> tag inside index.html), tour-step(0) lights up but tour-step(1) disappears. Note, the this is not my scenario and only is an observation.

I have a feeling I'm may be missing something fundamental. Thoughts appreciated.

**Comment by benmarch** [comment]
I think I understand your issue now, it has to do with the Angular lifecycle. Elements marked with ngIf are removed from the DOM when the value is false. That means that Angular--and therefore UI Tour--is unaware of the directives in the subtree. Any tour steps inside a falsey ngIf are essentially nonexistent. Since you start the tour before the ngIf is truthy, the tour starts with no steps, and therefore ends immediately. Once the ngIf is truthy, the subtree is compiled and linked by Angular and the step is registered with the tour in the post link function. The reason you need to use a $timeout when you start the tour in the directive is because you have it in the directive's controller which executes in the pre link phase (using $timeout defers to the next digest). If you put the start tour code in the post link function you won't need the $timeout.

If your steps are in different UI Router states, all you have to do is set useUiRouter to true, and set nextPath="nextState" and nextStep="nextStepId" and the rest will be handled by UI Tour. If you want a user action or the "Next" button on the tour step to switch an ngIf and wait for the next step to load, set nextPath="currentState" and nextStep="nextStepId". Internally this calls `tour.waitFor(nextStep)` and pauses the tour until the next step is registered. The reason you have to set nextPath is because it will otherwise hide the "Next" button since it won't know about the nonexistent step. See the docs for how nextStep/nextPath work.

The last piece is starting the tour. I don't recommend automatically starting the tour without an initial step loaded, and ideally a second step ready as well. One way to safely start it automatically is to add a stepAdded listener, and start the tour there. That way you will know that at least the first step will load. You can even listen for a specific step that has been added. See the docs about notifications.

I updated the [Plunker](https://plnkr.co/edit/wFkxmyGCdesCm462t9Rm?p=preview). Take a look at how the tour starts when the first step is added. I left some code in the directive to show how it _could_ be started within the directive. Uncommenting the first step works also. 

Everything you need to get your app working _should_ be available. Please refer to the readme if you are unsure of how certain features work, it is quite comprehensive. Let me know if you have tried a bunch of things and still can't get it to work.

**Comment by megabyzus** [comment]
@benmarch , thanks for your comprehensive and very helpful response.  Your first paragraph is what I suspected exactly.  Also, in the context of moving from state to state we often pass $stateParams and the next state behaves depending on those $stateParams.  Is the 'nextPath' in tour able to handle these?  For example what is the nextPath equivalent syntax for:

$state.go('statename', {opt1:'1', opt2:'2', ....})?

I don't see example syntax.

Thanks!

**Comment by benmarch** [comment]
Interesting, there is currently no way to do that easily. I can create a simpler API to handle async steps in the next release. For now, set nextPath to anything and create an onNext handler. In the handler, call tour.waitFor(nextStepName) which will pause the tour and wait. Then execute $state.go(..) and return a rejected promise. tour.waitFor() is not documented because it isn't intended to be used publicly, so use with caution. I will create a new issue that allows for easier access to steps that are not currently in the DOM.

**Comment by megabyzus** [comment]
What if I keep UiRouter false and, to go to the next state, I construct the required URL for that state and pass it to nextPath?  Will uiTour work?

**Comment by benmarch** [comment]
Theoretically that would work. All UI Tour does is call $location.path(nextPath) and wait for the next step to register itself.

**Comment by megabyzus** [comment]
Ok, thanks.  Considering your almost assuredly busy calendar, when do you expect to enable $statParam functionality?

**Comment by benmarch** [comment]
So my plan is to create an open API that makes no assumptions. So you would basically set a flag on the step that indicates that the next step must be loaded, and you would call $state.go(..) in the onNext handler for that step. That will give you full freedom to handle it how you want, it will even work without navigation (flipping an ngIf, for example). I will have that ready early next week as I am traveling this weekend (I should be able to implement that quickly while on the plane).

**Comment by megabyzus** [comment]
Roger that.  Thanks!

**Comment by megabyzus** [comment]
As an update, uiTour does go to the absolute URL to change from stateA to stateB without setting the `useUiRouter` flag.  However,  there seems to be an issue that is related to our previous conversation regarding instantiation of directives.  My stateB has N directives (with possible parent-child relationships) that are born at the 'same time'. If I put `tour-step` ids 0..N in each of these directives, **all** of them show in stateB instead of the expected one-at-a-time step through.  BTW, I don't have a filter on `tour.on('stepAdded') {startTour()}`.  This is almost the reverse of the previous conversation where many 'unknown to uiTour' directives are born 'at the same time', and as such, they all show their pertinent `tour-steps` because of an unfiltered `tour.on('stepAdded') {startTour()}` on each. So the question becomes what conditionals/filter do I need to handle this within 'tour.on(...)'.  How do I manage the tour-steps that are born 'at once' in the new $state where each is in its own directive? 

I've tried:
```
$scope.onTourReady = function (tour) {
	tour.on('stepAdded', function (step) {
		switch(step.stepId ) {
		    case "main00":
		    case "main10":
		        tour.start();
		        break;
		}
	});			
};
```	
where 'main10' is the 'last' tours-step (along with 'main20') born in stateB.  This works ok when I reload the stateB.  But if I come from stateA to stateB, both main10 and main20 tour-steps show. 
Thoughts? Note also, since multiple tour-steps are born, there is significant jitteriness which can be eliminated with ` tour-step-prevent-scrolling=true ` but not sure this is a viable option.

At the end, as you can imagine, i need to evaluate the ratio of custom work vs incorporating a 3d part lib for us is and I don't intend to monopolize your time.  I certainly appreciate your responses.

**Comment by benmarch** [comment]
Hey @megabyzus, sorry for the delay, I typed out a response but apparently never clicked the Comment button...

I'll say first that I don't recommend starting the tour automatically without user input, this is generally considered a bad user experience. However, if you have to do that, only start the tour when the first step is added, never start it more that once (that will technically just restart it... more or less). Change `tour.on('stepAdded')` to `tour.once('stepAdded')` which will only fire the first time. 

In this scenario, I recommend creating a single tour step at the top level that loads immediately when the page loads (page or view, either way it's the first thing to load) so that it starts with the first step. Then make sure all of your steps have proper `tour-step-order`s set. Beyond that, everything you described comes down to the Angular lifecycle. I recommend digging deep into the documentation and even the code so that you understand how and when each step target is compiled and linked. If set up properly, the only custom code you should need is the onStepAdded handler, and onNext/onPrev handlers for steps that transition the view. I'm not sure I can provide any more help without seeing your actual app in action.
