### ISSUE TITLE
Repositioning

### ISSUE THREAD

**Issue by piernik** [benmarch/angular-ui-tour#88]
I often have situation when popovers are wrongly positioned.
It happens when some parts are loaded by ajax.
Is there a possibility to calculate positions once again?

I'm using appendToBody

**Comment by benmarch** [comment]
Hey @piernik, there are some known positioning issues, mostly they come from the Angular Bootstrap $uibPosition service. I have corrected some of them but not all. I also don't have access to any sort of "reposition" method since that's all handled by Angular Bootstrap. I am currently working on removing the UIB dependency, but it is proving to be a difficult task. I will keep you informed.

**Comment by piernik** [comment]
I figured out what was the issue. I have directive in popover. It was rendered after position was calculated. Fixed width and height of element did the work - You can close it.

BTW. I would not abandon uib - it's up to You

**Comment by benmarch** [comment]
Hey @piernik I'm glad you got it working!

I definitely would rather not remove UIB, but it has a bunch of known bugs with positioning, and they tend to make breaking changes often enough to require breaking changes to this library. I'm still working on it, though, and if it turns out that it's best to keep it then I will. Thanks for the feedback!
