### ISSUE TITLE
move to next and previous step using arrow keys

### ISSUE THREAD

**Issue by diego-vieira** [benmarch/angular-ui-tour#9]
Hello, sample tour: http://bootstraptour.com/
If you press the right and left arrow key it'll navigate thru the steps.

There is a nice module that provides keyboard shortcuts
http://chieffancypants.github.io/angular-hotkeys/

If you're interested I can send a PR.

**Comment by benmarch** [comment]
Hi @diego-vieira, that would be awesome if you could create a PR for this feature. I was just thinking about including this yesterday while I was building the live demo page since it was a nightmare having to test the later steps. If you could include a configuration item to enable/disable the hotkeys as well I would appreciate that. Thanks!

**Comment by diego-vieira** [comment]
@benmarch I've just completed the hotkeys integration. Will send the PR in a few.
